version: 2
jobs:
  publish:
    docker:
      - image: rishabhpoddar/supertokens_python_driver_testing
    steps:
      - checkout
      - run: make dev-install
      - run: pip install setuptools wheel twine
      - run: python3 setup.py sdist bdist_wheel
      - run: twine upload --username $USERNAME --password $PASSWORD dist/*
  test:
    docker:
      - image: rishabhpoddar/supertokens_python_driver_testing
    steps:
      - add_ssh_keys:
          fingerprints:
            - "ef:05:b5:59:f2:35:fa:e9:62:bf:32:33:e1:7c:51:ee"
      - checkout
      - run: apt-get update
      - run: make dev-install
      - run: (cd .circleci/ && ./doTests.sh)
workflows:
  version: 2
  tagged-build:
    jobs:
      - publish:
          filters:
            tags:
              only: /v[0-9]+(\.[0-9]+)*/
            branches:
              ignore: /.*/
      - test:
          filters:
            tags:
              only: /dev-v[0-9]+(\.[0-9]+)*/
            branches:
              ignore: /.*/